### ISSUE TITLE
GUI is glitchy 

### ISSUE THREAD

**Issue by vanishakesswani** [HaikuArchives/BeVexed#16]
Whenever I try to start the app or try to change the difficulty mode something like this comes up for a moment : 

![small icon left](https://cloud.githubusercontent.com/assets/24365311/21360729/20524bc2-c707-11e6-96d4-fb7bbca5fef2.png)

**Comment by humdingerb** [comment]
"Whenever" you try to change difficulty?
I don't see that here. Can you list the steps to reproduce?

**Comment by vanishakesswani** [comment]
I have posted a video on GCI TASK page have a look . 
Link to the task : https://codein.withgoogle.com/dashboard/task-instances/5136575316885504/

**Comment by humdingerb** [comment]
Ah, OK now I see it. :)

**Comment by scottmc** [comment]
fixed by #25
