### ISSUE TITLE
Changing tile size shouldn't start a new game

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/BeVexed#27]
Changing the tile size currently starts a new game, where it should just keep the current play state and change the tile size.

**Comment by owenca** [comment]
Woah, that's bad. The bug has been there since the beginning, and I'm surprised that it hasn't been found until now. I'd love to work on this. Can you create a task for it?

**Comment by scottmc** [comment]
There is one...look for the task "Fix an Open Issue for any Application Hosted on HaikuArchives".  This bug may or may not be the same on HexVexed as some of the code is still there same between the two.

**Comment by owenca** [comment]
I already used it for my last task. Will there be an Edition 2 of the task?

**Comment by ojasva** [comment]
This still exists for me. Can someone verify?

**Comment by humdingerb** [comment]
Works here. Make sure you test with the latest commit in master.
