### ISSUE TITLE
No Background showing up

### ISSUE THREAD

**Issue by ojasva** [HaikuArchives/BeVexed#30]
![1](https://user-images.githubusercontent.com/44553464/48660146-d7162180-ea82-11e8-9335-cb50e94f0980.png)

**Comment by humdingerb** [comment]
It has to be packaged correctly. The Readme could point these things out.

**Comment by ojasva** [comment]
How can I get this done? I will be happy to update the ReadMe as well.

**Comment by humdingerb** [comment]
BeVexed isn't very thorough. It just checks in Ý/config/settings/Bevexed and /system/data/BeVexed for the backgrounds folder.

**Comment by scottmc** [comment]
HexVexed was forked from this and had a similar issue that has since been fixed.  Part of the fix was in the code, the other was in the recipe.  Make the some changes here and it should fix the problem.
